### ISSUE TITLE
WebStorm TSLint: "Object prototype may only be an Object or null: undefined"

### ISSUE THREAD

**Issue by JunyuanZheng** [Microsoft/tslint-microsoft-contrib#366]
I get:

```
TypeError: Object prototype may only be an Object or null: undefined

TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (native)
    at __extends (/Users/junyuanz/ViDeX/ViDeX/node_modules/tslint/lib/rules/noUnusedNewRule.js:23:9)
    at /Users/junyuanz/ViDeX/ViDeX/node_modules/tslint/lib/rules/noUnusedNewRule.js:58:5
    at Object.<anonymous> (/Users/junyuanz/ViDeX/ViDeX/node_modules/tslint/lib/rules/noUnusedNewRule.js:86:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
Process finished with exit code -1
```
Error when i enable webstorm TSlint support.

My configuration file is quite simple:

```
{
  "extends": "tslint-microsoft-contrib"
}
```

Is there any way that i can solve this issue?

Thanks!

**Comment by JunyuanZheng** [comment]
sorry, mb. it's webstorm's issue.
