### ISSUE TITLE
When default class is being used maxFuncBodyLengthRule is throwing a runtime error

### ISSUE THREAD

**Issue by german1983** [Microsoft/tslint-microsoft-contrib#393]
If you are using default classes and you try to use maxFuncBodyLengthRule the rule fails because class.name is undefined and it's trying to get class.name.text

`TypeError: Cannot read property 'text' of undefined
    at MaxFunctionBodyLengthRuleWalker.visitClassDeclaration (C:\Projects\Bell\sln.cd\cd-services-widget\node_modules\tslint-microsoft-contrib\maxFuncBodyLengthRule.js:94:42)
    at MaxFunctionBodyLengthRuleWalker.SyntaxWalker.visitNode (C:\Projects\Bell\sln.cd\cd-services-widget\node_modules\tslint\lib\language\walker\syntaxWalker.js:314:22)
    at C:\Projects\Bell\sln.cd\cd-services-widget\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
    at visitEachNode (C:\Projects\Bell\sln.cd\cd-services-widget\node_modules\typescript\lib\typescript.js:15956:30)
    at Object.forEachChild (C:\Projects\Bell\sln.cd\cd-services-widget\node_modules\typescript\lib\typescript.js:16136:24)
    at MaxFunctionBodyLengthRuleWalker.SyntaxWalker.walkChildren (C:\Projects\Bell\sln.cd\cd-services-widget\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:12)
    at MaxFunctionBodyLengthRuleWalker.SyntaxWalker.visitSourceFile (C:\Projects\Bell\sln.cd\cd-services-widget\node_modules\tslint\lib\language\walker\syntaxWalker.js:228:14)
    at MaxFunctionBodyLengthRuleWalker.SyntaxWalker.visitNode (C:\Projects\Bell\sln.cd\cd-services-widget\node_modules\tslint\lib\language\walker\syntaxWalker.js:482:22)
    at MaxFunctionBodyLengthRuleWalker.SyntaxWalker.walk (C:\Projects\Bell\sln.cd\cd-services-widget\node_modules\tslint\lib\language\walker\syntaxWalker.js:24:14)
    at Rule.AbstractRule.applyWithWalker (C:\Projects\Bell\sln.cd\cd-services-widget\node_modules\tslint\lib\language\rule\abstractRule.js:31:16)`

**Comment by Glavin001** [comment]
For example:

```
export default class extends BaseClass {
```

Will throw error:

```
TypeError: Cannot read property 'text' of undefined
```

However, the following will pass:

```
export default class SubClass extends BaseClass {
```

**Comment by JoshuaKGoldberg** [comment]
This looks like it should be as simple as if the `.name` property exists and bailing out if so.
