### ISSUE TITLE
The 'import-name' rule threw an error. Cannot read property 'importClause' of undefined

### ISSUE THREAD

**Issue by joseSantacruz** [microsoft/tslint-microsoft-contrib#667]
### Bug Report

-   **`tslint-microsoft-contrib` version**: 6.0.0
-   **TSLint version**:5.11.0
-   **TypeScript version**:3.1.6
-   **Running TSLint via**:  CLI 

#### TypeScript code being linted

```tsx
// code snippet
```

with `tslint.json` configuration:

```json
{
  "extends": ["tslint-microsoft-contrib"]
}
```

#### Actual behavior
```bash
The 'import-name' rule threw an error in '/Users/zerocooljs/Kushki/repo/kushki-usrv-snr/src/handler/SejiValidationHandler.ts':
TypeError: Cannot read property 'importClause' of undefined
    at ImportNameRuleWalker.visitImportDeclaration (/Users/zerocooljs/Kushki/repo/kushki-usrv-snr/node_modules/tslint-microsoft-contrib/importNameRule.js:138:54)
    at ImportNameRuleWalker.SyntaxWalker.visitNode (/Users/zerocooljs/Kushki/repo/kushki-usrv-snr/node_modules/tslint/lib/language/walker/syntaxWalker.js:392:22)
    at /Users/zerocooljs/Kushki/repo/kushki-usrv-snr/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/zerocooljs/Kushki/repo/kushki-usrv-snr/node_modules/typescript/lib/typescript.js:15788:30)
    at Object.forEachChild (/Users/zerocooljs/Kushki/repo/kushki-usrv-snr/node_modules/typescript/lib/typescript.js:16016:24)
    at ImportNameRuleWalker.SyntaxWalker.walkChildren (/Users/zerocooljs/Kushki/repo/kushki-usrv-snr/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at ImportNameRuleWalker.SyntaxWalker.visitSourceFile (/Users/zerocooljs/Kushki/repo/kushki-usrv-snr/node_modules/tslint/lib/language/walker/syntaxWalker.js:228:14)
    at ImportNameRuleWalker.SyntaxWalker.visitNode (/Users/zerocooljs/Kushki/repo/kushki-usrv-snr/node_modules/tslint/lib/language/walker/syntaxWalker.js:482:22)
    at ImportNameRuleWalker.SyntaxWalker.walk (/Users/zerocooljs/Kushki/repo/kushki-usrv-snr/node_modules/tslint/lib/language/walker/syntaxWalker.js:24:14)
    at Rule.AbstractRule.applyWithWalker (/Users/zerocooljs/Kushki/repo/kushki-usrv-snr/node_modules/tslint/lib/language/rule/abstractRule.js:31:16)
```
#### Expected behavior

Rule should not crash and no linting issue should be found.

**Comment by IllusionMH** [comment]
@jvanoostveen first one causes your exceptions, because there are no `importClause` in `ImportStatement` element.
Second should be processed just fine. Do you have problems with linter if you comment `import './polyfills';` and similar lines?

**Comment by jvanoostveen** [comment]
For this import, we disable the linting rule: 'no-import-side-effect'. No other issues with crashing rules. But not all Microsoft contrib rules are enabled, so not all are tested.

**Comment by joseSantacruz** [comment]
Hi @IllusionMH ,

this is the code of the SejiValidationHandler.ts

```typescript
/**
 * Seji Validation Handler
 */
import {
  BUILDER_API_GATEWAY_MIDDLEWARE,
  ContentTypeEnum,
  ERROR_API_MIDDLEWARE,
  IDENTIFIERS as ID,
  IHandler,
  INPUT_OUTPUT_LOGS,
  IRollbar,
  SETUP_MIDDLEWARE,
  SSM_MIDDLEWARE,
  StatusCodeEnum,
  VALIDATION_MIDDLEWARE,
} from "@kushki/core";
import { IDENTIFIERS } from "constant/Identifiers";
import { CONTAINER } from "infrastructure/Container";
import * as middy from "middy";
import "reflect-metadata";
import { ISejiService } from "repository/ISejiService";
import * as Rollbar from "rollbar";
import "source-map-support/register";

const CORE: IHandler = CONTAINER.get<IHandler>(ID.IHandler);
const ROLLBAR: Rollbar = CONTAINER.get<IRollbar>(ID.IRollbar).init();
const HANDLER: middy.IMiddy = middy(
  ROLLBAR.lambdaHandler(
    CORE.run<
      ISejiService, // Service Definition
      object
    >( // Service observable resolve type
      IDENTIFIERS.SejiService, // Service instance
      "validate", // Service Method,
      CONTAINER,
      ROLLBAR
    )
  )
)
  .use(SETUP_MIDDLEWARE(ROLLBAR))
  .use(INPUT_OUTPUT_LOGS(ROLLBAR))
  .use(ERROR_API_MIDDLEWARE(ROLLBAR))
  .use(SSM_MIDDLEWARE(ROLLBAR))
  .use(
    BUILDER_API_GATEWAY_MIDDLEWARE(
      ROLLBAR,
      ContentTypeEnum.JSON,
      StatusCodeEnum.OK,
      ContentTypeEnum.JSON,
      true
    )
  )
  .use(
    VALIDATION_MIDDLEWARE(ROLLBAR, {
      path: "seji_validate_pathparameters",
    })
  );

export { HANDLER };
```

And in case is usefull this is my current tsconfig

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "target": "es2016",
    "lib": ["es2017", "dom"],
    "sourceMap": true,
    "alwaysStrict": true,
    "baseUrl": ".",
    "types": ["mocha", "node", "reflect-metadata"],
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "noStrictGenericChecks": true,
    "paths": {
      "handler/*": ["src/handler/*"],
      "constant/*": ["src/constant/*"],
      "gateway/*": ["src/gateway/*"],
      "infrastructure/*": ["src/infrastructure/*"],
      "model/*": ["src/model/*"],
      "repository/*": ["src/repository/*"],
      "service/*": ["src/service/*"],
      "typings": ["typings.d.ts"],
      "utils/*": ["src/utils/*"],
      "error/*": ["src/error/*"],
      "types/*": ["types/*"]
    }
  },
  "exclude": ["node_modules"]
}

```

**Comment by joseSantacruz** [comment]
@IllusionMH after removing the imports the error disappears, my node version is 8.10.0. So I think the error should be the same

**Comment by IllusionMH** [comment]
Really strange. 
```
$ node -v
v8.10.0

$ ./node_modules/.bin/tslint -v
5.11.0

$ ./node_modules/.bin/tsc -v
Version 3.1.6

$ cat ./node_modules/tslint-microsoft-contrib/package.json | grep version
    "type": "version",
  "version": "6.0.0"
```

But still I can't get `TypeError: Cannot read property 'importClause' of undefined`. Will try to run in Linux container later.

The other strange thing is stack trace. Where traces are identical except only line numbers of last string:
```
    at ImportNameRuleWalker.visitImportDeclaration (/Users/zerocooljs/Kushki/repo/kushki-usrv-snr/node_modules/tslint-microsoft-contrib/importNameRule.js:138:54)
```

And in my case (for 6.0.0) I have 
```
    at ImportNameRuleWalker.visitImportDeclaration (C:\web\test\import-repro\node_modules\tslint-microsoft-contrib\importNameRule.js:127:31)
```
and `visitImportDeclaration` ends on 135 line, so exception cannot be on line 138 if there are some padding at the top of the module.

I'm out of ideas at this moment.

@joseSantacruz could you please show what params do you pass in `tslint` when run it from CLI? Is there a chance that there is `\r` line ending instead of `\n` ?

**Comment by joseSantacruz** [comment]
Hi @IllusionMH 

thi is the command that I'm running `npx tslint -t stylish --project tsconfig.json -c tslint.json 'src/**/*.ts'`

**Comment by dfee** [comment]
I just came across this too. It was because my `index.sass` file is imported like this: `import './index.sass'`.

I guess I'll wait for this to be merged into the next release.

**Comment by startswithaj** [comment]
I'm also finding I have the same error since updating package.

```
The 'import-name' rule threw an error in '/Users/jake/dev/citrus/citrus-client/src/app/app.module.ts':
TypeError: Cannot read property 'name' of undefined
```

It's imports like these
`
import 'rxjs/add/operator/switchMap';
`

I've tried disabling the rule for that line, but it must try and parse it anyway.

**Comment by Cayan** [comment]
I receive this error when I try to import `core-js`

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is deprecated** and no longer accepting pull requests other than security fixes. See #876. ☠️ 
We recommend you instead use **[typescript-eslint](https://typescript-eslint.io)** to lint your TypeScript code with **ESLint**. ✅

👋 It was a pleasure open sourcing with you!
