### ISSUE TITLE
ReferenceError: Lint is not defined

### ISSUE THREAD

**Issue by staeke** [Microsoft/tslint-microsoft-contrib#89]
Just tried to use this by

```sh
npm install typescript
npm install tslint
npm install tslint-microsoft-contrib
./node_modules/tslint/bin/tslint -r node_modules/tslint-microsoft-contrib/ my-test-file.ts
```

with a ```tslint.json``` with

```
{
    "rules": {
        "no-document-write": true
    }
}
```

...and ```my-test-file.ts``` with
```
document.write('test');
```

which resulted in:

```
ReferenceError: Lint is not defined
    at Object.<anonymous> (/Users/staffan/dev/tslint-test/node_modules/tslint-microsoft-contrib/utils/ErrorTolerantWalker.js:32:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/staffan/dev/tslint-test/node_modules/tslint-microsoft-contrib/noDocumentWriteRule.js:7:27)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

**Comment by staeke** [comment]
I noticed that using tslint 3.1.1 works. It seems the error appears from 3.2.0 and up

**Comment by HamletDRC** [comment]
Unfortunately we do not yet support tslint 3 or TypeScript 1.7. 
We'll try to get to it soon 
#87

**Comment by HamletDRC** [comment]
I'll try to get to it this weekend

**Comment by staeke** [comment]
cool...if you don't for some reason, maybe it's a good idea to change your npm dependency version constraints?
