### ISSUE TITLE
Add support for tslint@^6.0.0

### ISSUE THREAD

**Issue by shaunco** [microsoft/tslint-microsoft-contrib#898]
This project currently only supports tslint@^5.1.0, but now that tslint 6 is out, it would be great to have support.

The only issue I ran in to when I ignored the dependency mismatch warning was that it seems to be finding invalid regex expressions inside of quoted strings _(I tried single quotes, double quotes, and back-tick quotes)_:
```
The 'export-name' rule threw an error in 'R:/MyProjPath/src/config/index.ts':
SyntaxError: Invalid regular expression: /^{
.
.
.
        prefix: process.env.API_PREFIX || '/api',
.
.
.

}\..+/: Nothing to repeat
    at new RegExp (<anonymous>)
    at validateExport (R:\MyProjPath\node_modules\tslint-microsoft-contrib\exportNameRule.js:146:21)
    at walk (R:\MyProjPath\node_modules\tslint-microsoft-contrib\exportNameRule.js:170:13)
    at Rule.AbstractRule.applyWithFunction (R:\MyProjPath\node_modules\tslint\lib\language\rule\abstractRule.js:40:9)
    at Rule.apply (R:\MyProjPath\node_modules\tslint-microsoft-contrib\exportNameRule.js:28:21)
    at Linter.applyRule (R:\MyProjPath\node_modules\tslint\lib\linter.js:215:29)
    at R:\MyProjPath\node_modules\tslint\lib\linter.js:156:85
    at Object.flatMap (R:\MyProjPath\node_modules\tslint\lib\utils.js:161:29)
    at Linter.getAllFailures (R:\MyProjPath\node_modules\tslint\lib\linter.js:156:32)
    at Linter.lint (R:\MyProjPath\node_modules\tslint\lib\linter.js:111:33)
```

**Comment by brndkfr** [comment]
This project is read-only and [archive](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-archiving-repositories) mode.
